### PR TITLE
Use the output of multirpc to report the down or timed out nodes

### LINKED ISSUE #197: `join_cluster` command reports the wrong node down
When the local node tries to join a node that doesn't exit, it reports itself as down instead of the remote node.

Note: the output is correct in the sense that the node `rabbit@mars` is up but no `rabbit` application is running, as `stop_app` has been called just before, but it is not the reason why the command failed.

```
./rabbitmqctl join_cluster rabbit@neptuno
Clustering node rabbit@mars with rabbit@neptuno
Error: unable to connect to node 'rabbit@mars': nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@mars]

rabbit@mars:
  * connected to epmd (port 4369) on mars
  * node rabbit@mars up, 'rabbit' application not running
  * running applications on rabbit@mars: [lager,ranch_proxy_protocol,ranch,
                                          ssl,public_key,crypto,inets,xmerl,
                                          jsx,asn1,goldrush,compiler,
                                          syntax_tools,sasl,stdlib,kernel]
  * suggestion: start_app on rabbit@mars

current node details:
- node name: rabbitmqcli49@mars
- home dir: /Users/dparracorbacho
- cookie hash: iCekESKlAouYCMe/hLn89g==
```

### PR DESCRIPTION
**Pull request by dcorbacho**
Most commands do rpc's only to the target node, but join_cluster
triggers an rpc between nodes. If the rpc to the remote down returns
down/timeout, we must use that value to run the diagnostics.
Using the node from command options in diagnostics will report as down
the wrong node.

Closes #197

### CODE REVIEW

File: lib/rabbitmqctl.ex [hunk 1]
```diff
@@ -251,6 +251,18 @@ defmodule RabbitMQCtl do
     exit({:shutdown, code})
   end
 
+  defp format_error({:error, {:badrpc_multi, :nodedown, [node | _]} = result}, opts, _) do
+    diagnostics = get_node_diagnostics(node)
+    {:error, ExitCodes.exit_code_for(result),
+     "Error: unable to connect to node '#{node}': nodedown\n" <>
+     diagnostics}
+  end
+  defp format_error({:error, {:badrpc_multi, :timeout, [node | _]} = result}, opts, _) do
```
Comment (lukebakken) [inline lib/rabbitmqctl.ex]: I think this is a duplicate of `format_error` on line 254

Comment (dcorbacho) [inline lib/rabbitmqctl.ex]: Wrong error message, fixed now. Thanks!

File: lib/rabbitmqctl.ex [hunk 2]
```diff
@@ -251,6 +251,17 @@ defmodule RabbitMQCtl do
...
+    op = CommandModules.module_to_command(module)
```
Comment (michaelklishin) [inline lib/rabbitmqctl.ex]: This line fails compilation for me as `module` isn't defined:

```
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/antares/Development/RabbitMQ/umbrella.git/deps/parallel_stream/mix.exs:9

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/antares/Development/RabbitMQ/umbrella.git/deps/parallel_stream/mix.exs:10

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/antares/Development/RabbitMQ/umbrella.git/deps/csv/mix.exs:9

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/antares/Development/RabbitMQ/umbrella.git/deps/csv/mix.exs:10

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/antares/Development/RabbitMQ/umbrella.git/deps/json/mix.exs:10

Compiling 80 files (.ex)
warning: variable "module" does not exist and is being expanded to "module()", please use parentheses to remove the ambiguity or change the variable name
  lib/rabbitmqctl.ex:261

warning: variable "opts" is unused
  lib/rabbitmqctl.ex:254


== Compilation error on file lib/rabbitmqctl.ex ==
** (CompileError) lib/rabbitmqctl.ex:261: undefined function module/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

Comment (michaelklishin) [inline lib/rabbitmqctl.ex]: Addressed in b8b2dd85232221a9940b1e2ed3863e43b6ae0866.
