### PR TITLE
Execution environment validation

### LINKED ISSUE #214: Error message in CLI when rabbit application is stopped
The new cli is missing the error message when rabbit application is stopped (e.g. via `stop_app`) and needs to be running.

The old cli:

```
Error: rabbit application is not running on node rabbit@localhost.
 * Suggestion: start it with "rabbitmqctl start_app" and try again
```

The new cli:

```
Error:
{:badrpc, {:EXIT, {:aborted, {:no_exists, [:rabbit_vhost, "/"]}}}}
```

### PR DESCRIPTION
**Pull request by michaelklishin**
This is a follow-up attempt after #215 was considered to be an experiment that did not work out.

In this attempt we [will] introduce

 * More fine grained command execution steps
 * `validate_execution_environment/2`: an optional callback that can be used by commands to check that, say, files are readable or something else is acceptable, separately from CLI argument validation in `validate/2`

Fixes #214.

### CODE REVIEW

File: lib/rabbitmqctl.ex [hunk 1]
```diff
@@ -67,13 +67,75 @@ defmodule RabbitMQCtl do
...
         end)
     end
   end
 
+  defp maybe_validate_rabbit_app_state(_command, _arguments, %{offline: true}) do
+    :ok
+  end
+  defp maybe_validate_rabbit_app_state(command, arguments, options) do
+    required_state = case function_exported?(command, :required_rabbit_app_state, 2) do
+                       false -> :running
```
Comment (hairyhum) [inline lib/rabbitmqctl.ex]: I still disagree on this default. Adding a line to 70 files now is not that hard as having to maintain this default.

File: lib/rabbitmq/cli/core/helpers.ex [hunk 2]
```diff
@@ -187,6 +187,14 @@ defmodule RabbitMQ.CLI.Core.Helpers do
     :net_adm.ping(node) == :pong
   end
 
+  def rabbit_app_running?(%{node: node, timeout: timeout}) do
```
Comment (hairyhum) [inline lib/rabbitmq/cli/core/helpers.ex]: Should we make it clear that this function has 3 return types? For example `running | stopped | {error, _}`?

File: lib/rabbitmqctl.ex (hunk 1 above)
Comment (lukebakken) [inline lib/rabbitmqctl.ex]: @hairyhum Is your concern that someone will add a command in the future but forget to take this default into consideration?

File: lib/rabbitmqctl.ex [hunk 3]
```diff
@@ -67,13 +67,75 @@ defmodule RabbitMQCtl do
...
-          validate_and_run_command(options, command, arguments)
-          |> handle_command_output(command, options, unparsed_command, output_fun)
+          # The code below implements a tiny decision tree that has
+          # to do with CLI argument and environment state validation.
+
+          # validate CLI arguments
+          case command.validate(arguments, options) do
+            :ok ->
+              # then validate RabbitMQ application state (running or not)
+              case maybe_validate_rabbit_app_state(command, arguments, options) do
```
Comment (lukebakken) [inline lib/rabbitmqctl.ex]: That depends on how the command implements `required_rabbit_app_state`.

File: lib/rabbitmq/cli/command_behaviour.ex [hunk 4]
```diff
@@ -29,7 +29,9 @@ defmodule RabbitMQ.CLI.CommandBehaviour do
                       scopes: 0,
                       usage_additional: 0,
                       switches: 0,
-                      aliases: 0
+                      aliases: 0,
+                      required_rabbit_app_state: 2,
+                      validate_execution_environment: 2
```
Comment (lukebakken) [inline lib/rabbitmq/cli/command_behaviour.ex]: I would like to see `validate_execution_environment` take the `offline` switch into account in the function's implementation, rather than in the `rabbitmqctl.ex` file.

Comment (michaelklishin) [inline lib/rabbitmq/cli/command_behaviour.ex]: Every command either needs RabbitMQ running or stopped. It's not something optional. Under what circumstances will a command require a running app when `--offline` is passed?

I mentioned this in https://github.com/rabbitmq/rabbitmq-cli/pull/215#issuecomment-320220048.

Comment (lukebakken) [inline lib/rabbitmq/cli/command_behaviour.ex]: > It's not something optional

`rabbitmq-diagnostics memory_breakdown` doesn't care about the `rabbit` app at all, and does not have an `offline` switch, for one example. I think several of those diagnostics commands don't care about the `rabbit` app.

File: lib/rabbitmqctl.ex (hunk 1 above)
Comment (michaelklishin) [inline lib/rabbitmqctl.ex]: Adding a line to 70 commands *and* every command introduced in the future, where most commands need a running app, is annoying. I don't expect this default to change.

File: lib/rabbitmq/cli/core/helpers.ex (hunk 2 above)
Comment (michaelklishin) [inline lib/rabbitmq/cli/core/helpers.ex]: We can add a type spec. Is it what you are asking for?

File: lib/rabbitmq/cli/command_behaviour.ex (hunk 4 above)
Comment (michaelklishin) [inline lib/rabbitmq/cli/command_behaviour.ex]: How useful is `rabbitmq-diagnostics memory_breakdown` on a VM with `rabbit` not running? We are not trying to reinvent Erlang tooling after all.

Commands that are ambivalent about the state of the `rabbit` app either operate on an unused data directory (`rename_cluster_node`) or Erlang VM. There's only a handful of them. Are they worth going through every single command and adding a validation function plus requiring every other command that exists or will be added to be updated the same way?

If we fold both validations into `validate_execution_environment/2`, what should happen when it is not defined? No validations should be performed at all?

Comment (hairyhum) [inline lib/rabbitmq/cli/command_behaviour.ex]: We have at least 17 commands, which do not care about rabbit app status:
- encode
- decode
- list_ciphers
- list_hashes 
- environment
- eval
- exec
- help
- hipe_compile
- stop
- shutdown
- cipher_suites
- erlang_cookie_hash
- erlang_version
- memory_breakdown
- server_version
- status

My point is that this behaviour is already a problem in this PR (handling `badrpc` errors) and will create more problems as more commands are added.

File: lib/rabbitmqctl.ex (hunk 1 above)
Comment (hairyhum) [inline lib/rabbitmqctl.ex]: Adding a validator which does nothing just to avoid this default validation is even more annoying. Because it will not tell anything about the command, but work around the system defaults.

File: lib/rabbitmq/cli/core/helpers.ex (hunk 2 above)
Comment (michaelklishin) [inline lib/rabbitmq/cli/core/helpers.ex]: But they are predicates. They have to perform I/O so there's potential for other failures. How should they be named if not as predicates?

File: lib/rabbitmqctl.ex [hunk 5]
```diff
@@ -67,13 +67,52 @@ defmodule RabbitMQCtl do
...
+            :ok ->
+              # then optionally validate execution environment
+              case maybe_validate_execution_environment(command, arguments, options) do
+                :ok   -> proceed_to_execution(command, arguments, options)
+                other -> other
+              end
+            other -> other
+            # handle_command_output will handle all the errors
+            # among other things
+          end |> handle_command_output(command, options, unparsed_command, output_fun)
```
Comment (hairyhum) [inline lib/rabbitmqctl.ex]: If we have `validation_failure` from both validation steps, how do we differentiate which message should we format? I'm talking about "Given: ... Usage: ..." message, which does not make much sense for `validate_execution_environment` errors.

File: lib/rabbitmq/cli/core/validators.ex [hunk 6]
```diff
@@ -17,14 +17,16 @@
...
-
   def chain([validator | rest], args) do
     case apply(validator, args) do
-      :ok -> chain(rest, args);
-      err -> err
+      :ok                        -> chain(rest, args)
+      {:ok, _}                   -> chain(rest, args)
+      {:validation_failure, err} -> {:validation_failure, err}
+      {:error, err}              -> {:validation_failure, err}
+      other                      -> other
```
Comment (hairyhum) [inline lib/rabbitmq/cli/core/validators.ex]: It could be just me, but I would prefer validation functions to be strictly typed. Otherwise how do we know that `handle_command_output` can handle the return value?

File: lib/rabbitmqctl.ex (hunk 5 above)
Comment (michaelklishin) [inline lib/rabbitmqctl.ex]: Maybe it needs a new key.

Comment (michaelklishin) [inline lib/rabbitmqctl.ex]: I tried using a different key and a different `RabbitMQCtl#validation_error/4` function. They end up looking very similarly. Printing a formatted error and CLI flags still makes sense.

We can change `Error` in the CLI flag validation to be something like `Error (invalid arguments)` and for execution env validation use just `Error` (I cannot think of a suitable generic clarification, "execution environment" is something only contributors can make sense of). Does that sound like an improvement?

Comment (hairyhum) [inline lib/rabbitmqctl.ex]: The main confusion here is that "Given ... Usage ..." text is taking most of the message and draws attention from the actual error.
And that's ok if the error is in the arguments and you can tell if your arguments are invalid by just looking at them.
But in case of environment, we should make the actual error more visible than usage information. Maybe for argument validation too.

File: lib/rabbitmq/cli/command_behaviour.ex [hunk 7]
```diff
@@ -29,7 +30,11 @@ defmodule RabbitMQ.CLI.CommandBehaviour do
                       scopes: 0,
                       usage_additional: 0,
                       switches: 0,
-                      aliases: 0
+                      aliases: 0,
+                      # validates execution environment, e.g. file presence,
+                      # whether RabbitMQ is in an expected state on a node, etc
+                      validate_execution_environment: 2
+
```
Comment (hairyhum) [inline lib/rabbitmq/cli/command_behaviour.ex]: This callback could use a typespec.

File: lib/rabbitmqctl.ex [hunk 8]
```diff
@@ -62,26 +62,65 @@ defmodule RabbitMQCtl do
...
+              # then optionally validate execution environment
+              case maybe_validate_execution_environment(command, arguments, options) do
+                :ok                        ->
+                  result = proceed_to_execution(command, arguments, options)
+                  handle_command_output(result, command, options, output_fun);
+                {:validation_failure, err} ->
+                  argument_validation_error_output(err, command, unparsed_command, options)
+              end
+            {:validation_failure, err} ->
+              environment_validation_error_output(err, command, unparsed_command, options)
```
Comment (hairyhum) [inline lib/rabbitmqctl.ex]: Should it be `argument_validation_error_output` instead? And `environment_validation_error_output` on line 84?

File: lib/rabbitmq/cli/ctl/commands/decode_command.ex [hunk 9]
```diff
@@ -43,13 +51,7 @@ defmodule RabbitMQ.CLI.Ctl.Commands.DecodeCommand do
...
   end
 
-  def switches() do
-      [
-        cipher: :atom,
-        hash: :atom,
-        iterations: :integer
-      ]
-  end
+  use RabbitMQ.CLI.Core.RequiresRabbitAppRunning
```
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/decode_command.ex]: Decode command does not need the app to be running. It does not even need a node to be running.

File: lib/rabbitmq/cli/ctl/commands/encode_command.ex [hunk 10]
```diff
@@ -43,13 +51,7 @@ defmodule RabbitMQ.CLI.Ctl.Commands.EncodeCommand do
...
   end
 
-  def switches() do
-      [
-        cipher: :atom,
-        hash: :atom,
-        iterations: :integer
-      ]
-    end
+  use RabbitMQ.CLI.Core.RequiresRabbitAppRunning
```
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/encode_command.ex]: Same as decode command. No need for the app to be running.

File: lib/rabbitmq/cli/ctl/commands/environment_command.ex [hunk 11]
```diff
@@ -18,19 +18,22 @@ defmodule RabbitMQ.CLI.Ctl.Commands.EnvironmentCommand do
...
+  def scopes(), do: [:ctl, :diagnostics]
+
+  def merge_defaults(args, opts), do: {args, opts}
+
   def validate([_|_], _), do: {:validation_failure, :too_many_args}
   def validate(_, _), do: :ok
-  def merge_defaults(args, opts), do: {args, opts}
 
-  def formatter(), do: RabbitMQ.CLI.Formatters.Erlang
+  use RabbitMQ.CLI.Core.RequiresRabbitAppRunning
```
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/environment_command.ex]: Environment command does not need the rabbit app to be running.

File: lib/rabbitmq/cli/ctl/commands/decode_command.ex (hunk 9 above)
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/decode_command.ex]: The decode command does not need the rabbit app to be running. It does not even need a node to be running.

File: lib/rabbitmq/cli/ctl/commands/encode_command.ex (hunk 10 above)
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/encode_command.ex]: The encode command does not need the rabbit app to be running.

File: lib/rabbitmq/cli/ctl/commands/environment_command.ex (hunk 11 above)
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/environment_command.ex]: The environment command does not need the rabbit app to be running.

File: lib/rabbitmq/cli/ctl/commands/eval_command.ex [hunk 12]
```diff
@@ -37,6 +34,8 @@ defmodule RabbitMQ.CLI.Ctl.Commands.EvalCommand do
     end
   end
 
+  use RabbitMQ.CLI.Core.RequiresRabbitAppRunning
```
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/eval_command.ex]: The eval command does not need the rabbit app to be running.

File: lib/rabbitmq/cli/ctl/commands/exec_command.ex [hunk 13]
```diff
@@ -46,6 +44,8 @@ defmodule RabbitMQ.CLI.Ctl.Commands.ExecCommand do
     end
   end
 
+  use RabbitMQ.CLI.Core.RequiresRabbitAppRunning
```
Comment (hairyhum) [inline lib/rabbitmq/cli/ctl/commands/exec_command.ex]: The exec command does not need the rabbit app to be running. It does not even need a node to be running

File: lib/rabbitmq/cli/ctl/commands/environment_command.ex (hunk 11 above)
Comment (michaelklishin) [inline lib/rabbitmq/cli/ctl/commands/environment_command.ex]: Technically it doesn't but if you stop the app, it's environment won't be printed. I'd expect 99% of users use this command to get that, not e.g. effective `ssl` settings.
