### PR TITLE
Handle error in `rabbit_mnesia:cluster_nodes/1` on cluster_status command

### LINKED ISSUE #199: Unhandled exception in `cluster_status` command when mnesia is not accesible
While restarting the node, a call to `cluster_status` might return an exception because the command is not checking if `rabbit_mnesia:cluster_nodes/1` returns an error.

```
Cluster status of node rabbit2@mars ...
Error:
#{'__exception__' => true,
  '__struct__' => 'Elixir.Protocol.UndefinedError',
  description => <<>>,
  protocol => 'Elixir.Enumerable',
  value => {error,{corrupt_or_missing_cluster_files,{error,enoent},{error,enoent}}}}
 Stacktrace [{'Elixir.Enumerable','impl_for!',1,
                 [{file,"lib/enum.ex"},{line,1}]},
             {'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,116}]},
             {'Elixir.Enum',map,2,[{file,"lib/enum.ex"},{line,1776}]},
             {'Elixir.RabbitMQ.CLI.Ctl.Commands.ClusterStatusCommand',run,2,
                 [{file,
                      "lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex"},
                  {line,34}]},
             {'Elixir.RabbitMQCtl',maybe_run_command,3,
                 [{file,"lib/rabbitmqctl.ex"},{line,171}]},
             {'Elixir.RabbitMQCtl','-exec_command/2-fun-0-',5,
                 [{file,"lib/rabbitmqctl.ex"},{line,70}]},
             {'Elixir.RabbitMQCtl',main,1,
                 [{file,"lib/rabbitmqctl.ex"},{line,43}]},
             {'Elixir.Kernel.CLI','-exec_fun/2-fun-0-',3,
                 [{file,"lib/kernel/cli.ex"},{line,76}]}]
```

### PR DESCRIPTION
**Pull request by dcorbacho**
If the error is ignored, an Enum exception is triggered which is not
meaningful for the final user. Notifying that something is wrong accessing
to Mnesia files provides a hint. Can be eventually reproduced while
the node is restarting.

Fixes #199

### CODE REVIEW

File: lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex [hunk 1]
```diff
@@ -33,6 +33,8 @@ defmodule RabbitMQ.CLI.Ctl.Commands.ClusterStatusCommand do
         case :rabbit_misc.rpc_call(node_name, :rabbit_mnesia, :cluster_nodes, [:running]) do
           {:badrpc, _} = err ->
             err
+          {:error, {corrupt_or_missing_cluster_files, _, _}} = err ->
```
Comment (lukebakken) [inline lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex]: Note: I don't know Elixir very well 😄

I can see that the error tuple atoms are not prefixed with `:` in the stack trace (#199):

```
{error,{corrupt_or_missing_cluster_files,{error,enoent},{error,enoent}}}}
```

In the code here, I see that the atom `:error` uses a colon. Does this mean that `corrupt_or_missing_cluster_files` should also use one?

Comment (michaelklishin) [inline lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex]: Yes, as all atoms in Elixir start with a colon.
